name: limo1_bridge
from_domain: 67
to_domain: 66
bidirectional: True
# ===========================
#         TOPICS
# ===========================
topics:
  # État général du robot
  /limo1/mission_state:
    type: std_msgs/msg/String

  # Carte générée
  /limo1/map:
    type: nav_msgs/msg/OccupancyGrid

# ===========================
#         SERVICES
# ===========================
services:
  /limo1/identify_robot:
    type: std_srvs/srv/Trigger

# ===========================
#         ACTIONS
# ===========================
actions:
  /limo1/do_mission:
    type: limo_interfaces/action/DoMission
