name: limo2_bridge
from_domain: 67
to_domain: 66
bidirectional: True
# ===========================
#         TOPICS
# ===========================
topics:
  # État général du robot
  /limo2/mission_state:
    type: std_msgs/msg/String

  # Carte générée
  /limo2/map:
    type: nav_msgs/msg/OccupancyGrid

# ===========================
#         SERVICES
# ===========================
services:
  /limo2/identify_robot:
    type: std_srvs/srv/Trigger

# ===========================
#         ACTIONS
# ===========================
actions:
  /limo2/do_mission:
    type: limo_interfaces/action/DoMission
